apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tetg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hieg-tenant/rhtap-demo-app/hacbs-test-project-tetg@sha256:309de1573bc1734feeaabc8302e7031e15ca610c133e7a0a7061314517b34ac2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
