apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tetg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hieg-tenant/rhtap-demo-app/hacbs-test-project-tetg@sha256:7f4a68acdee7195db03c68e4c0401b61ce14ebdf40f9106a17c2b842fb4ab886
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
